package ez.dork.stock.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import ez.dork.stock.domain.StockName;
import ez.dork.stock.domain.StockNameExample;

public interface StockNameMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stock_name
	 * 
	 * @mbggenerated Fri Dec 06 23:23:50 CST 2013
	 */
	int countByExample(StockNameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stock_name
	 * 
	 * @mbggenerated Fri Dec 06 23:23:50 CST 2013
	 */
	int deleteByExample(StockNameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stock_name
	 * 
	 * @mbggenerated Fri Dec 06 23:23:50 CST 2013
	 */
	int deleteByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stock_name
	 * 
	 * @mbggenerated Fri Dec 06 23:23:50 CST 2013
	 */
	int insert(StockName record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stock_name
	 * 
	 * @mbggenerated Fri Dec 06 23:23:50 CST 2013
	 */
	int insertSelective(StockName record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stock_name
	 * 
	 * @mbggenerated Fri Dec 06 23:23:50 CST 2013
	 */
	List<StockName> selectByExample(StockNameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stock_name
	 * 
	 * @mbggenerated Fri Dec 06 23:23:50 CST 2013
	 */
	StockName selectByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stock_name
	 * 
	 * @mbggenerated Fri Dec 06 23:23:50 CST 2013
	 */
	int updateByExampleSelective(@Param("record") StockName record, @Param("example") StockNameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stock_name
	 * 
	 * @mbggenerated Fri Dec 06 23:23:50 CST 2013
	 */
	int updateByExample(@Param("record") StockName record, @Param("example") StockNameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stock_name
	 * 
	 * @mbggenerated Fri Dec 06 23:23:50 CST 2013
	 */
	int updateByPrimaryKeySelective(StockName record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stock_name
	 * 
	 * @mbggenerated Fri Dec 06 23:23:50 CST 2013
	 */
	int updateByPrimaryKey(StockName record);

	List<StockName> selectAll();

}