package ez.dork.stock.mapper;

import ez.dork.stock.domain.Stock;
import ez.dork.stock.domain.StockKey;

public interface StockMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stock
	 * 
	 * @mbggenerated Sun Nov 10 01:06:58 CST 2013
	 */
	int deleteByPrimaryKey(StockKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stock
	 * 
	 * @mbggenerated Sun Nov 10 01:06:58 CST 2013
	 */
	int insert(Stock record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stock
	 * 
	 * @mbggenerated Sun Nov 10 01:06:58 CST 2013
	 */
	int insertSelective(Stock record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stock
	 * 
	 * @mbggenerated Sun Nov 10 01:06:58 CST 2013
	 */
	Stock selectByPrimaryKey(StockKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stock
	 * 
	 * @mbggenerated Sun Nov 10 01:06:58 CST 2013
	 */
	int updateByPrimaryKeySelective(Stock record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table stock
	 * 
	 * @mbggenerated Sun Nov 10 01:06:58 CST 2013
	 */
	int updateByPrimaryKey(Stock record);
}