package ez.dork.stock.mapper;

import ez.dork.stock.domain.EarnMoney;
import ez.dork.stock.domain.Strategy;
import ez.dork.stock.domain.StrategyExample;
import ez.dork.stock.domain.StrategyKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface StrategyMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table strategy
	 * 
	 * @mbggenerated Wed Nov 13 23:28:15 CST 2013
	 */
	int countByExample(StrategyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table strategy
	 * 
	 * @mbggenerated Wed Nov 13 23:28:15 CST 2013
	 */
	int deleteByExample(StrategyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table strategy
	 * 
	 * @mbggenerated Wed Nov 13 23:28:15 CST 2013
	 */
	int deleteByPrimaryKey(StrategyKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table strategy
	 * 
	 * @mbggenerated Wed Nov 13 23:28:15 CST 2013
	 */
	int insert(Strategy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table strategy
	 * 
	 * @mbggenerated Wed Nov 13 23:28:15 CST 2013
	 */
	int insertSelective(Strategy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table strategy
	 * 
	 * @mbggenerated Wed Nov 13 23:28:15 CST 2013
	 */
	List<Strategy> selectByExample(StrategyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table strategy
	 * 
	 * @mbggenerated Wed Nov 13 23:28:15 CST 2013
	 */
	Strategy selectByPrimaryKey(StrategyKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table strategy
	 * 
	 * @mbggenerated Wed Nov 13 23:28:15 CST 2013
	 */
	int updateByExampleSelective(@Param("record") Strategy record, @Param("example") StrategyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table strategy
	 * 
	 * @mbggenerated Wed Nov 13 23:28:15 CST 2013
	 */
	int updateByExample(@Param("record") Strategy record, @Param("example") StrategyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table strategy
	 * 
	 * @mbggenerated Wed Nov 13 23:28:15 CST 2013
	 */
	int updateByPrimaryKeySelective(Strategy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table strategy
	 * 
	 * @mbggenerated Wed Nov 13 23:28:15 CST 2013
	 */
	int updateByPrimaryKey(Strategy record);

	List<Strategy> getStrategyList(@Param("code") String code);

	List<EarnMoney> getAllStockOrderByEarnMoney();

	void truncate();
}