package ez.dork.stock.domain;

public class Stock extends StockKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.open
     *
     * @mbggenerated Tue Nov 12 15:09:34 CST 2013
     */
    private Double open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.high
     *
     * @mbggenerated Tue Nov 12 15:09:34 CST 2013
     */
    private Double high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.low
     *
     * @mbggenerated Tue Nov 12 15:09:34 CST 2013
     */
    private Double low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.close
     *
     * @mbggenerated Tue Nov 12 15:09:34 CST 2013
     */
    private Double close;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.volumn
     *
     * @mbggenerated Tue Nov 12 15:09:34 CST 2013
     */
    private Integer volumn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.open
     *
     * @return the value of stock.open
     *
     * @mbggenerated Tue Nov 12 15:09:34 CST 2013
     */
    public Double getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.open
     *
     * @param open the value for stock.open
     *
     * @mbggenerated Tue Nov 12 15:09:34 CST 2013
     */
    public void setOpen(Double open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.high
     *
     * @return the value of stock.high
     *
     * @mbggenerated Tue Nov 12 15:09:34 CST 2013
     */
    public Double getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.high
     *
     * @param high the value for stock.high
     *
     * @mbggenerated Tue Nov 12 15:09:34 CST 2013
     */
    public void setHigh(Double high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.low
     *
     * @return the value of stock.low
     *
     * @mbggenerated Tue Nov 12 15:09:34 CST 2013
     */
    public Double getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.low
     *
     * @param low the value for stock.low
     *
     * @mbggenerated Tue Nov 12 15:09:34 CST 2013
     */
    public void setLow(Double low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.close
     *
     * @return the value of stock.close
     *
     * @mbggenerated Tue Nov 12 15:09:34 CST 2013
     */
    public Double getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.close
     *
     * @param close the value for stock.close
     *
     * @mbggenerated Tue Nov 12 15:09:34 CST 2013
     */
    public void setClose(Double close) {
        this.close = close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.volumn
     *
     * @return the value of stock.volumn
     *
     * @mbggenerated Tue Nov 12 15:09:34 CST 2013
     */
    public Integer getVolumn() {
        return volumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.volumn
     *
     * @param volumn the value for stock.volumn
     *
     * @mbggenerated Tue Nov 12 15:09:34 CST 2013
     */
    public void setVolumn(Integer volumn) {
        this.volumn = volumn;
    }
}