package ez.dork.stock.domain;

public class StockKey {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock.code
	 * @mbggenerated  Wed Nov 13 23:28:15 CST 2013
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock.date
	 * @mbggenerated  Wed Nov 13 23:28:15 CST 2013
	 */
	private String date;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock.code
	 * @return  the value of stock.code
	 * @mbggenerated  Wed Nov 13 23:28:15 CST 2013
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock.code
	 * @param code  the value for stock.code
	 * @mbggenerated  Wed Nov 13 23:28:15 CST 2013
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock.date
	 * @return  the value of stock.date
	 * @mbggenerated  Wed Nov 13 23:28:15 CST 2013
	 */
	public String getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock.date
	 * @param date  the value for stock.date
	 * @mbggenerated  Wed Nov 13 23:28:15 CST 2013
	 */
	public void setDate(String date) {
		this.date = date;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((code == null) ? 0 : code.hashCode());
		result = prime * result + ((date == null) ? 0 : date.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		StockKey other = (StockKey) obj;
		if (code == null) {
			if (other.code != null)
				return false;
		} else if (!code.equals(other.code))
			return false;
		if (date == null) {
			if (other.date != null)
				return false;
		} else if (!date.equals(other.date))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "StockKey [code=" + code + ", date=" + date + "]";
	}
    
}