package ez.dork.stock.domain;

public class StockName {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_name.code
	 * @mbggenerated  Fri Dec 06 23:23:50 CST 2013
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_name.name
	 * @mbggenerated  Fri Dec 06 23:23:50 CST 2013
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_name.kind
	 * @mbggenerated  Fri Dec 06 23:23:50 CST 2013
	 */
	private Integer kind;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_name.code
	 * @return  the value of stock_name.code
	 * @mbggenerated  Fri Dec 06 23:23:50 CST 2013
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_name.code
	 * @param code  the value for stock_name.code
	 * @mbggenerated  Fri Dec 06 23:23:50 CST 2013
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_name.name
	 * @return  the value of stock_name.name
	 * @mbggenerated  Fri Dec 06 23:23:50 CST 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_name.name
	 * @param name  the value for stock_name.name
	 * @mbggenerated  Fri Dec 06 23:23:50 CST 2013
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_name.kind
	 * @return  the value of stock_name.kind
	 * @mbggenerated  Fri Dec 06 23:23:50 CST 2013
	 */
	public Integer getKind() {
		return kind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_name.kind
	 * @param kind  the value for stock_name.kind
	 * @mbggenerated  Fri Dec 06 23:23:50 CST 2013
	 */
	public void setKind(Integer kind) {
		this.kind = kind;
	}

	@Override
	public String toString() {
		return "StockName [code=" + code + ", name=" + name + ", kind=" + kind + "]";
	}
    
}