package ez.dork.stock.domain;

public class StockKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.code
     *
     * @mbggenerated Sun Nov 10 01:06:58 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.date
     *
     * @mbggenerated Sun Nov 10 01:06:58 CST 2013
     */
    private String date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.code
     *
     * @return the value of stock.code
     *
     * @mbggenerated Sun Nov 10 01:06:58 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.code
     *
     * @param code the value for stock.code
     *
     * @mbggenerated Sun Nov 10 01:06:58 CST 2013
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.date
     *
     * @return the value of stock.date
     *
     * @mbggenerated Sun Nov 10 01:06:58 CST 2013
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.date
     *
     * @param date the value for stock.date
     *
     * @mbggenerated Sun Nov 10 01:06:58 CST 2013
     */
    public void setDate(String date) {
        this.date = date;
    }
}