package ez.dork.stock.domain;

public class StrategyKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column strategy.code
	 * @mbggenerated  Fri Dec 06 23:23:50 CST 2013
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column strategy.buy_date
	 * @mbggenerated  Fri Dec 06 23:23:50 CST 2013
	 */
	private String buyDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column strategy.code
	 * @return  the value of strategy.code
	 * @mbggenerated  Fri Dec 06 23:23:50 CST 2013
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column strategy.code
	 * @param code  the value for strategy.code
	 * @mbggenerated  Fri Dec 06 23:23:50 CST 2013
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column strategy.buy_date
	 * @return  the value of strategy.buy_date
	 * @mbggenerated  Fri Dec 06 23:23:50 CST 2013
	 */
	public String getBuyDate() {
		return buyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column strategy.buy_date
	 * @param buyDate  the value for strategy.buy_date
	 * @mbggenerated  Fri Dec 06 23:23:50 CST 2013
	 */
	public void setBuyDate(String buyDate) {
		this.buyDate = buyDate;
	}
}