package ez.dork.stock.domain;

public class Strategy extends StrategyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.amount
     *
     * @mbggenerated Wed Nov 13 23:28:15 CST 2013
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.price
     *
     * @mbggenerated Wed Nov 13 23:28:15 CST 2013
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy.amount
     *
     * @return the value of strategy.amount
     *
     * @mbggenerated Wed Nov 13 23:28:15 CST 2013
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy.amount
     *
     * @param amount the value for strategy.amount
     *
     * @mbggenerated Wed Nov 13 23:28:15 CST 2013
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy.price
     *
     * @return the value of strategy.price
     *
     * @mbggenerated Wed Nov 13 23:28:15 CST 2013
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy.price
     *
     * @param price the value for strategy.price
     *
     * @mbggenerated Wed Nov 13 23:28:15 CST 2013
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}