package ez.dork.stock.domain;

public class StrategyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.code
     *
     * @mbggenerated Wed Nov 13 23:28:15 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.date
     *
     * @mbggenerated Wed Nov 13 23:28:15 CST 2013
     */
    private String date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy.code
     *
     * @return the value of strategy.code
     *
     * @mbggenerated Wed Nov 13 23:28:15 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy.code
     *
     * @param code the value for strategy.code
     *
     * @mbggenerated Wed Nov 13 23:28:15 CST 2013
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy.date
     *
     * @return the value of strategy.date
     *
     * @mbggenerated Wed Nov 13 23:28:15 CST 2013
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy.date
     *
     * @param date the value for strategy.date
     *
     * @mbggenerated Wed Nov 13 23:28:15 CST 2013
     */
    public void setDate(String date) {
        this.date = date;
    }
}